# This code is generated by PyUIbuilder: https://github.com/PaulleDemon/PyUIBuilder

import customtkinter as ctk

class Page2:
    def __init__(self, tabview, tab):
        self.tabview = tabview
        self.tab = tab
        
        self.build_page()
        
    def button_function(self):
        self.tabview.set("tab 1")

    def build_page(self):
        main = ctk.CTkFrame(self.tab)
        main.pack(side=ctk.TOP, padx=10, pady=10, anchor='nw', fill="y")

        frame = ctk.CTkFrame(master=main)
        frame.configure(fg_color="#EDECEC")
        frame.pack(side=ctk.TOP, padx=10, pady=10, anchor='nw', fill="y")

        label = ctk.CTkLabel(master=frame, text="PÁGINA 2")
        label.configure(fg_color="#E4E2E2", text_color="#000", width=104, height=42)
        label.pack(side=ctk.LEFT, padx=10, pady=10, anchor='nw')

        entry = ctk.CTkEntry(master=frame, placeholder_text="placeholder text")
        entry.configure(fg_color="#fff", text_color="#000", border_color="#000", width=120, height=40)
        entry.pack(side=ctk.LEFT, padx=10, pady=10, anchor='nw')

        button = ctk.CTkButton(master=main, text="Button", command=self.button_function)
        button.configure(fg_color="#029CFF", text_color="#fff", border_color="#000", width=80, height=40)
        button.pack(side=ctk.TOP, padx=10, pady=10, anchor='nw')
