# This code is generated by PyUIbuilder: https://github.com/PaulleDemon/PyUIBuilder

import customtkinter as ctk
from CTkDatePicker import CTkDatePicker

class Page1:
    def __init__(self, tabview, tab):
        self.tabview = tabview
        self.tab = tab
        
        self.build_page()
        
    def button_function(self):
        self.tabview.set("tab 2")

    def build_page(self):
        main = ctk.CTkFrame(master=self.tab) 
        main.pack(side=ctk.TOP, padx=10, pady=10, anchor='nw', fill="y")


        labelName = ctk.CTkLabel(master=main, text="Nome: ")
        labelName.pack(side=ctk.LEFT, padx=10, pady=10, anchor='nw')

        entryName = ctk.CTkEntry(master=main, placeholder_text="Insira o seu Nome")
        entryName.pack(side=ctk.LEFT, padx=10, pady=10, anchor='nw')

        labelDate = ctk.CTkLabel(master=main, text="Data: ")
        labelDate.pack(side=ctk.LEFT, padx=10, pady=10, anchor='nw')

        entryDate = CTkDatePicker(main)
        entryDate.pack(side=ctk.LEFT, padx=10, pady=10, anchor='nw')
        
        button = ctk.CTkButton(master=main, text="CTkButton", command=self.button_function)
        button.place(relx=0.5, rely=0.9, anchor=ctk.CENTER)

        return main
