# This code is generated by PyUIbuilder: https://github.com/PaulleDemon/PyUIBuilder

import customtkinter as ctk

main = ctk.CTk()
main.configure(fg_color="#23272D")
main.title("Main Window")

framenavbar = ctk.CTkFrame(master=main)
framenavbar.configure(fg_color="#EDECEC")
framenavbar.pack(side=ctk.LEFT, padx=10, pady=10, anchor='nw', fill="y")

frameimage = ctk.CTkFrame(master=framenavbar)
frameimage.configure(fg_color="#EDECEC")
frameimage.pack(side=ctk.TOP, padx=30, pady=30, anchor='center')

label = ctk.CTkLabel(master=frameimage, text="Reservas")
label.configure(fg_color="#E4E2E2", text_color="#000", width=80, height=40)
label.pack(side=ctk.TOP, padx=10, pady=10, anchor='center')

buttonhome = ctk.CTkButton(master=framenavbar, text="Página Inicial")
buttonhome.configure(fg_color="#029CFF", text_color="#fff", border_color="#000", cursor="hand2", width=333, height=52)
buttonhome.pack(side=ctk.TOP, padx=30, pady=30, anchor='center')

buttonreserva = ctk.CTkButton(master=framenavbar, text="Reservas")
buttonreserva.configure(fg_color="#029CFF", text_color="#fff", border_color="#000", cursor="hand2", width=337, height=52)
buttonreserva.pack(side=ctk.TOP, padx=30, pady=30, anchor='center')

framereservabuttons = ctk.CTkFrame(master=framenavbar)
framereservabuttons.configure(fg_color="#EDECEC")
framereservabuttons.pack(side=ctk.TOP, padx=30, pady=30, anchor='center')

buttonreservacriar = ctk.CTkButton(master=framereservabuttons, text="Criar")
buttonreservacriar.configure(fg_color="#029CFF", text_color="#fff", border_color="#000", width=185, height=38)
buttonreservacriar.pack(side=ctk.TOP, padx=10, pady=10, anchor='center')

buttonreservalista = ctk.CTkButton(master=framereservabuttons, text="Lista")
buttonreservalista.configure(fg_color="#029CFF", text_color="#fff", border_color="#000", width=185, height=44)
buttonreservalista.pack(side=ctk.TOP, padx=10, pady=10, anchor='center')

buttonrequisicao = ctk.CTkButton(master=framenavbar, text="Requisições")
buttonrequisicao.configure(fg_color="#029CFF", text_color="#fff", border_color="#000", cursor="hand2", width=333, height=54)
buttonrequisicao.pack(side=ctk.TOP, padx=30, pady=30, anchor='center')

framerequisicaobuttons = ctk.CTkFrame(master=framenavbar)
framerequisicaobuttons.configure(fg_color="#EDECEC")
framerequisicaobuttons.pack(side=ctk.TOP, padx=30, pady=30, anchor='center')

buttonrequisicaocriar = ctk.CTkButton(master=framerequisicaobuttons, text="Criar")
buttonrequisicaocriar.configure(fg_color="#029CFF", text_color="#fff", border_color="#000", width=164, height=42)
buttonrequisicaocriar.pack(side=ctk.TOP, padx=10, pady=10, anchor='nw')

buttonrequisicaolista = ctk.CTkButton(master=framerequisicaobuttons, text="Lista")
buttonrequisicaolista.configure(fg_color="#029CFF", text_color="#fff", border_color="#000", width=165, height=42)
buttonrequisicaolista.pack(side=ctk.TOP, padx=10, pady=10, anchor='nw')

frametest = ctk.CTkFrame(master=main)
frametest.configure(fg_color="#EDECEC")
frametest.pack(side=ctk.LEFT, padx=10, pady=10, anchor='nw', fill="both", expand = True)


main.mainloop()